name: job_connect
description: A modern job search and connection platform
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  smooth_page_indicator: ^1.1.0
  timeago_flutter: ^3.7.0 # Let's also update the pubspec.yaml to add the timeago package.
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Assets must be indented properly
  assets:
    - assets/images/
    - assets/icons/
